# Generated by Django 5.0.1 on 2024-01-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='color',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
